config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :task_lists do
  	resources :task_items do
  		member do
  			patch :complete
  		end
  	end
  end
  root 'static_pages#index'
end

app/models/task_item.rb
class TaskItem < ActiveRecord::Base
  belongs_to :task_list
  belongs_to :user

  validates :title , :description, :duedate,  presence: true


  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }

  def completed?
    !completed_at.blank?
  end

  def toggle_completion!
  	if completed?
  		update_attribute(:completed_at, nil)
  	else
  		update_attribute(:completed_at, Time.now)
  	end
  end

end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
	has_many :task_items, dependent: :destroy
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :task_lists
	has_many :task_items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_all_tasks
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @task_list.user_id = current_user.id
  end
  private

  def set_all_tasks
      @task_lists = TaskList.all
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_all_tasks


  def index

  end
  private

  def set_all_tasks
      @task_lists = TaskList.all
      @task_list = TaskList.new
  end
end

app/controllers/task_items_controller.rb
class TaskItemsController < ApplicationController

	before_action :find_task_list
	before_action :find_task_item, except: [:create]


	def create
		@task_item = @task_list.task_items.create(task_items_params)
		@task_item.user_id = current_user.id
		if @task_item.save
			redirect_to @task_list, notice: "Task item successfully added"
		else
			redirect_to root_path, notice: "Please check if you fill out all fields"
		end
	end

	def edit
	end

	def update
      if @task_item.update(task_items_params)
        redirect_to @task_list, notice: 'Task list was successfully updated.'
      else
        render :edit
      end
  end

	def destroy
		@task_item.destroy
		redirect_to @task_list
	end

	def complete
		 @task_item.toggle_completion!
		 redirect_to @task_list, notice: "Task item updated."
	end

	private

	def task_items_params
		params.require(:task_item).permit(:title, :description, :duedate)
	end

	def find_task_list
		@task_list = TaskList.find(params[:task_list_id])
	end

	def find_task_item
		@task_item = @task_list.task_items.find(params[:id])
	end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]
  before_action :set_all_tasks, only: [:index, :show, :edit]
  
  def index
  end

  def show
  end

  def new
    @task_list = current_user.task_lists.build
  end

  def edit
  end

  def create
    @task_list = current_user.task_lists.create(task_list_params)
    @task_list.user_id = current_user.id
      if @task_list.save
        redirect_to @task_list, notice: 'Task list was successfully created.'
      else
        render :new
    end
  end

  def update
      if @task_list.update(task_list_params)
        redirect_to @task_list, notice: 'Task list was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @task_list.destroy
    redirect_to task_lists_url, notice: 'Task list was successfully destroyed.'
  end

  private
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end
    def task_list_params
      params.require(:task_list).permit(:name)
    end
    def set_all_tasks
      @task_lists = TaskList.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackTask</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

<div class="flash-message">
	<% flash.each do |name, msg| %>
		<div class="alert alert-<%= name == :notice ? "warning" : "success"  %>">
			<%= msg %>
		</div>
	<% end %>
</div>
<div class="row">
	<%= render 'task_lists/nav' %>
	<%= yield %>
</div>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/static_pages/index.html.erb
<!-- Main Content -->


<% if user_signed_in? %>
	<div class="container-fluid">
		<div class="side-body">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 landing-page">
					<h1 class="task_list_title_index">Let the Tasks be strong within you!</h1>
				</div>
					
<% else %>
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 landing-page">
				<h1 class="task_list_title_index">Welcome to TrackTask!</h1>
				<br>
				<p class="index_text">Keep track of your daily tasks, and never ever forget anythig.</p>
				<p class="index_text">
					<%= link_to "Login", new_user_session_path, class:"login_button" %> | 
					<%= link_to "Sign Up", new_user_registration_path ,class:"login_button"%></p>
<% end %>	

		</div>
	</div>
</div>

app/views/task_items/_task_item.html.erb
<% if task_item.completed? %>
	<div class="panel panel-default grey" >
	<div class="panel-body">
<% else %>
	<div class="panel panel-default" >
	<div class="panel-body">
<% end %>

<% if task_item.completed? %>
	<%= link_to complete_task_list_task_item_path(@task_list, task_item), method: :patch, class: "check-item" do  %>
		<i class="fa fa-reply"></i>
	<% end %>

	<%= link_to task_list_task_item_path(@task_list, task_item.id), method: :delete, data: {confirm: "Are yo sure?"}, class: "delete-item" do %>
	<i class="fa fa-trash"></i>
	<% end %>

	<div class="status-item">
		<strike><%= task_item.title %></strike> <i class="text-muted" style="font-size:.8em;">created by <%= task_item.user.email  %></i>
	</div>

<% else %>
	<%= link_to complete_task_list_task_item_path(@task_list, task_item), method: :patch, class: "check-item" do %>
		<i class="fa fa-check"></i>
	<% end %>
	
	<%= link_to task_list_task_item_path(@task_list, task_item.id), method: :delete, data: {confirm: "Are yo sure?"}, class: "delete-item" do %>
	<i class="fa fa-trash"></i>
	<% end %>
	<%= link_to edit_task_list_task_item_path(@task_list, task_item.id), class: "delete-item" do %>
		<i class="fa fa-edit"></i> | 
	<% end %>
	<p class="delete-item"><i><b>Due date:</b><%= (task_item.duedate).strftime("%B %e, %Y") %></i></p>

	<div class="status-item">
		<%= link_to task_item.title, "#" + task_item.id.to_s , class: "task_item_title", 'data-toggle' => "collapse", 'aria-expanded' => "false", 'aria-controls' => "task_description" %>
		<i class="text-muted" style="font-size:.8em;">created by <%= task_item.user.email  %></i>
		
	</div>
	<div class="collapse" id="<%= task_item.id.to_s %>">
		  <div class="well">
		    <p><b>Description</b></p>
		    <p><%= task_item.description %></p>
			
		  </div>
		</div>
<% end %>

	</div>
</div>


app/views/task_items/_task_item_edit_form.html.erb

<%= simple_form_for([@task_list, @task_item]) do |f| %>
	<form class="form-horizontal">
			<div class="form-group">
			<%= f.input :title %>
			<%= f.input :description %>
			<%= f.text_field :duedate, class:"datepicker" %>
			<br>
			<br>
			<%= f.button :submit %>
			</div>
	</form>
<% end %>
	

app/views/task_items/_task_item_form.html.erb

	<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		      	<div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			        <h4 class="modal-title" id="myModalLabel">Create new Task Item</h4>
		     	</div>
			    <div class="modal-body">
				     <%= simple_form_for ([@task_list, @task_list.task_items.build]) , {validate: true} do |f|  %>
				        <%= f.input :title %>
				        <%= f.input :description %>
				        <div class="form-group">
				        <%= f.text_field :duedate, placeholder:" Set due date...", class: "datepicker", :data => {provide: 'datepicker'} %>
				        </div>
			    </div>

			    <div class="modal-footer">
				    <%= f.button :submit %>
				</div>
			   	<% end %>
		</div>
	</div>
</div>




app/views/task_items/edit.html.erb
<div class="container-fluid">
    <div class="side-body">
	    <div class="row">
	        <div class="col-lg-12">
	        <br>
				<%= render 'task_item_edit_form' %>
			</div>
		</div>
	</div>
</div>

app/views/task_lists/_nav.html.erb
 <% if user_signed_in? %>
    <div class="side-menu">
        <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <div class="brand-wrapper">
                    <!-- Hamburger -->
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                <!-- Brand -->
                <div class="brand-name-wrapper">
                <%= image_tag ("logo-ruby.png"), class: "navbar-brand" %><%= link_to "TrackTask", root_path, class: "navbar-brand" %>
                </div>
                <!-- Search -->
                <a data-toggle="collapse" href="#search" class="btn btn-default" id="search-trigger">
                <span class="glyphicon glyphicon-search"></span>
                </a>
                <!-- Search body -->
                <div id="search" class="panel-collapse collapse">
                    <div class="panel-body">
                        <form class="navbar-form" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default "><span class="glyphicon glyphicon-ok"></span></button>
                        </form>
                    </div>
                </div>
            </div>
            </div>
            <!-- Main Menu -->
            <div class="side-menu-container">
                <ul class="nav navbar-nav">
                <li class="sidebar_task"><%= link_to raw('<i class="fa fa-user sidebar_icon"></i>') + "Signed in as: " + current_user.email %></li>
                    <li class="sidebar_task"><%= link_to raw('<i class="fa fa-user sidebar_icon"></i>') + "Sign Out" , destroy_user_session_path, method: :delete %></li>
                    <li><%= link_to "New Task", new_task_list_path, id: "new_task", remote: true %></li>
                    
                    <% if user_signed_in? %>
                        
                            <% @task_lists.each do |task_list| %>
                                <% if task_list.user_id == current_user.id %>
                                    <li class="sidebar_task"><%= link_to raw('<i class="fa fa-star sidebar_icon"></i>' + task_list.name), task_list %></li>
                                <% end %>                            
                            <% end %>
                    <% end %>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </div>
<% end %>



app/views/task_lists/_task_list_form.html.erb
<%= simple_form_for(@task_list) do |f| %>
  <% if @task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% @task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="">
    <%= f.input :name, placeholder: "task name...", label:false %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<div class="container-fluid">
    <div class="side-body">
	    <div class="row">
	        <div class="col-lg-12">
	        <br>
				<%= render 'task_list_form' %>
			</div>
		</div>
	</div>
</div>

app/views/task_lists/index.html.erb
<!-- Main Content -->
<div class="container-fluid">
    <div class="side-body">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3 landing-page">

				<% if user_signed_in? %>
						<h1 class="task_list_title">Let the Tasks be strong within you!</h1>
				<% else %>
					<h1>Welcome!</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus quae quod quis, nobis dignissimos nisi obcaecati libero pariatur nihil non labore quaerat iste totam commodi cumque magnam voluptatem asperiores maiores?</p>
					<p>Please feel free to <%= link_to "Login", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %></p>
				<% end %>	
				
			</div>
		</div>
    </div>
</div>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form' %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/new.js.erb
$("#new_task").hide().after('<%= j render ('task_list_form') %>')

app/views/task_lists/show.html.erb
<div class="container-fluid">
    <div class="side-body">
	    <div class="row">
	        <div class="col-lg-12">
				<h3 class="task_list_title"> <%= @task_list.name %> 
				<%= link_to raw('<i class="fa fa-edit"></i>'), edit_task_list_path %>
				<%= link_to raw('<i class="fa fa-trash"></i>'), task_list_path(@task_list), method: :delete, data: { confirm: 'Are you sure?' } %>
				<p class="created_at">created by <%= @task_list.user.email %></p></h3>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-lg-12">
				<div class="input-group">
					<div class="input-group-addon"><b>+</b></div>
					<input type="text" class="form-control" data-toggle="modal" data-target="#myModal" placeholder: "Add Task Item" />
				</div>
				<%= render 'task_items/task_item_form' %>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-lg-12">
				<% if !@task_list.task_items.incomplete.blank? %>
					<%= render @task_list.task_items.incomplete %>
				<% end %>
			</div>
		</div>
		<br>
		
		<div class="row">
			<div class="col-lg-12">

				<div class="completed_items_wrapper">
					<%= link_to "Show completed items", "#toggle_completed_items", id: "completed_items" %>
				</div>
				<% if !@task_list.task_items.complete.blank? %>
					<div id="toggle_completed_items">
						<%= render @task_list.task_items.complete %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>